# Generated by Django 5.2.7 on 2025-12-05 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=16)),
                ('week_start', models.DateField()),
                ('games_played', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('best_time_sec', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to='core.gametype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', 'game_type', 'difficulty'],
                'unique_together': {('user', 'game_type', 'difficulty', 'week_start')},
            },
        ),
    ]
